"""initial schema

Revision ID: 6be55fd8e2b1
Revises: 
Create Date: 2026-08-29 20:14:54.953021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6be55fd8e2b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('perishability_level', sa.Integer(), nullable=False),
    sa.Column('expected_shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('required_min_temp_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('required_max_temp_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('SAFE', 'MONITOR', 'CHECK', 'PRIORITY_CHECK', 'DO_NOT_SERVE', 'MAINTENANCE_ALERT', 'SUPPLIER_REVIEW', 'FRAUD_REVIEW', 'INVESTIGATE', name='action_enum'), nullable=False),
    sa.Column('department', sa.Enum('KITCHEN', 'MAINTENANCE', 'PROCUREMENT', 'AUDIT', 'INVESTIGATION', name='department_enum'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dimensions_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feature_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit_type', sa.String(length=30), nullable=False),
    sa.Column('target_temp_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.String(length=120), nullable=True),
    sa.Column('distributor_id', sa.String(length=120), nullable=True),
    sa.Column('batch_prefix', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_batch_prefix'), 'suppliers', ['batch_prefix'], unique=False)
    op.create_index(op.f('ix_suppliers_distributor_id'), 'suppliers', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_suppliers_warehouse_id'), 'suppliers', ['warehouse_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'KITCHEN', 'PROCUREMENT', 'MAINTENANCE', 'AUDITOR', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=60), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_unit_id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anomaly_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('residual', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('trend_per_day', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('estimated_days_to_threshold', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['storage_unit_id'], ['storage_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_anomalies_storage_unit_id'), 'storage_anomalies', ['storage_unit_id'], unique=False)
    op.create_table('storage_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_unit_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['storage_unit_id'], ['storage_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_readings_storage_unit_id'), 'storage_readings', ['storage_unit_id'], unique=False)
    op.create_index(op.f('ix_storage_readings_ts'), 'storage_readings', ['ts'], unique=False)
    op.create_table('unit_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_unit_id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('affected_food_batch_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['storage_unit_id'], ['storage_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_incidents_storage_unit_id'), 'unit_incidents', ['storage_unit_id'], unique=False)
    op.create_table('consumption_anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_item_id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('z_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pct_change', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cross_referenced_food_risk', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_anomalies_food_item_id'), 'consumption_anomalies', ['food_item_id'], unique=False)
    op.create_table('consumption_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_item_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_consumed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_records_food_item_id'), 'consumption_records', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_consumption_records_ts'), 'consumption_records', ['ts'], unique=False)
    op.create_table('food_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_item_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('storage_unit_id', sa.Uuid(), nullable=True),
    sa.Column('batch_code', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_opened', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['storage_unit_id'], ['storage_units.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_batches_batch_code'), 'food_batches', ['batch_code'], unique=False)
    op.create_index(op.f('ix_food_batches_food_item_id'), 'food_batches', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_food_batches_storage_unit_id'), 'food_batches', ['storage_unit_id'], unique=False)
    op.create_index(op.f('ix_food_batches_supplier_id'), 'food_batches', ['supplier_id'], unique=False)
    op.create_table('label_scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_batch_id', sa.Uuid(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_batch_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_class', sa.String(length=20), nullable=False),
    sa.Column('prediction_horizon', sa.String(length=10), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_food_batch_id'), 'risk_predictions', ['food_batch_id'], unique=False)
    op.create_table('supplier_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('food_batch_id', sa.Uuid(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_size_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_delay_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('defect_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('rejected_quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('expiry_margin_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_deliveries_supplier_id'), 'supplier_deliveries', ['supplier_id'], unique=False)
    op.create_table('wastage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_item_id', sa.Uuid(), nullable=False),
    sa.Column('food_batch_id', sa.Uuid(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_wasted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('estimated_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wastage_records_food_item_id'), 'wastage_records', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_wastage_records_ts'), 'wastage_records', ['ts'], unique=False)
    op.create_table('label_anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_scan_id', sa.Uuid(), nullable=False),
    sa.Column('food_batch_id', sa.Uuid(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anomaly_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ),
    sa.ForeignKeyConstraint(['label_scan_id'], ['label_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_anomalies_label_scan_id'), 'label_anomalies', ['label_scan_id'], unique=False)
    op.create_table('supplier_anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_delivery_id', sa.Uuid(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('deviating_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['supplier_delivery_id'], ['supplier_deliveries.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_anomalies_supplier_id'), 'supplier_anomalies', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_anomalies_supplier_id'), table_name='supplier_anomalies')
    op.drop_table('supplier_anomalies')
    op.drop_index(op.f('ix_label_anomalies_label_scan_id'), table_name='label_anomalies')
    op.drop_table('label_anomalies')
    op.drop_index(op.f('ix_wastage_records_ts'), table_name='wastage_records')
    op.drop_index(op.f('ix_wastage_records_food_item_id'), table_name='wastage_records')
    op.drop_table('wastage_records')
    op.drop_index(op.f('ix_supplier_deliveries_supplier_id'), table_name='supplier_deliveries')
    op.drop_table('supplier_deliveries')
    op.drop_index(op.f('ix_risk_predictions_food_batch_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_table('label_scans')
    op.drop_index(op.f('ix_food_batches_supplier_id'), table_name='food_batches')
    op.drop_index(op.f('ix_food_batches_storage_unit_id'), table_name='food_batches')
    op.drop_index(op.f('ix_food_batches_food_item_id'), table_name='food_batches')
    op.drop_index(op.f('ix_food_batches_batch_code'), table_name='food_batches')
    op.drop_table('food_batches')
    op.drop_index(op.f('ix_consumption_records_ts'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_food_item_id'), table_name='consumption_records')
    op.drop_table('consumption_records')
    op.drop_index(op.f('ix_consumption_anomalies_food_item_id'), table_name='consumption_anomalies')
    op.drop_table('consumption_anomalies')
    op.drop_index(op.f('ix_unit_incidents_storage_unit_id'), table_name='unit_incidents')
    op.drop_table('unit_incidents')
    op.drop_index(op.f('ix_storage_readings_ts'), table_name='storage_readings')
    op.drop_index(op.f('ix_storage_readings_storage_unit_id'), table_name='storage_readings')
    op.drop_table('storage_readings')
    op.drop_index(op.f('ix_storage_anomalies_storage_unit_id'), table_name='storage_anomalies')
    op.drop_table('storage_anomalies')
    op.drop_table('food_items')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_warehouse_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_distributor_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_batch_prefix'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('storage_units')
    op.drop_table('model_versions')
    op.drop_table('incidents')
    op.drop_table('food_categories')
    # ### end Alembic commands ###
