"""foodwise: ledger, data_source, occupancy, storage config, quarantine

Revision ID: c1291a7fea03
Revises: 6be55fd8e2b1
Create Date: 2026-08-30 09:25:35.903727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1291a7fea03'
down_revision: Union[str, None] = '6be55fd8e2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occupancy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_guests', sa.Integer(), nullable=True),
    sa.Column('actual_guests', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('data_source', sa.Enum('REAL', 'DEMO', name='data_source_enum'), nullable=False, server_default='DEMO'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_records_data_source'), 'occupancy_records', ['data_source'], unique=False)
    op.create_index(op.f('ix_occupancy_records_record_date'), 'occupancy_records', ['record_date'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_batch_id', sa.Uuid(), nullable=False),
    sa.Column('txn_type', sa.Enum('DELIVERY', 'CONSUMPTION', 'WASTE', 'ADJUSTMENT', 'TRANSFER', name='transaction_type_enum'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('data_source', sa.Enum('REAL', 'DEMO', name='data_source_enum'), nullable=False, server_default='DEMO'),
    sa.ForeignKeyConstraint(['food_batch_id'], ['food_batches.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_data_source'), 'inventory_transactions', ['data_source'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_food_batch_id'), 'inventory_transactions', ['food_batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_ts'), 'inventory_transactions', ['ts'], unique=False)
    op.add_column('consumption_records', sa.Column('food_batch_id', sa.Uuid(), nullable=True))
    op.add_column('consumption_records', sa.Column('meal', sa.String(length=30), nullable=True))
    op.add_column('consumption_records', sa.Column('department', sa.String(length=60), nullable=True))
    op.add_column('consumption_records', sa.Column('recorded_by', sa.Uuid(), nullable=True))
    op.add_column('consumption_records', sa.Column('data_source', sa.Enum('REAL', 'DEMO', name='data_source_enum'), nullable=False, server_default='DEMO'))
    op.create_index(op.f('ix_consumption_records_data_source'), 'consumption_records', ['data_source'], unique=False)
    op.create_index(op.f('ix_consumption_records_food_batch_id'), 'consumption_records', ['food_batch_id'], unique=False)
    op.create_foreign_key(None, 'consumption_records', 'users', ['recorded_by'], ['id'])
    op.create_foreign_key(None, 'consumption_records', 'food_batches', ['food_batch_id'], ['id'])
    op.add_column('food_batches', sa.Column('is_quarantined', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('food_batches', sa.Column('quarantine_reason', sa.String(length=500), nullable=True))
    op.add_column('food_batches', sa.Column('data_source', sa.Enum('REAL', 'DEMO', name='data_source_enum'), nullable=False, server_default='DEMO'))
    op.create_index(op.f('ix_food_batches_data_source'), 'food_batches', ['data_source'], unique=False)
    op.add_column('storage_readings', sa.Column('remarks', sa.String(length=500), nullable=True))
    op.add_column('storage_readings', sa.Column('recorded_by', sa.Uuid(), nullable=True))
    op.add_column('storage_readings', sa.Column('data_source', sa.Enum('REAL', 'DEMO', name='data_source_enum'), nullable=False, server_default='DEMO'))
    op.create_index(op.f('ix_storage_readings_data_source'), 'storage_readings', ['data_source'], unique=False)
    op.create_foreign_key(None, 'storage_readings', 'users', ['recorded_by'], ['id'])
    op.add_column('storage_units', sa.Column('min_safe_temp_c', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('storage_units', sa.Column('max_safe_temp_c', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('supplier_deliveries', sa.Column('data_source', sa.Enum('REAL', 'DEMO', name='data_source_enum'), nullable=False, server_default='DEMO'))
    op.create_index(op.f('ix_supplier_deliveries_data_source'), 'supplier_deliveries', ['data_source'], unique=False)
    op.add_column('wastage_records', sa.Column('department', sa.String(length=60), nullable=True))
    op.add_column('wastage_records', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('wastage_records', sa.Column('recorded_by', sa.Uuid(), nullable=True))
    op.add_column('wastage_records', sa.Column('data_source', sa.Enum('REAL', 'DEMO', name='data_source_enum'), nullable=False, server_default='DEMO'))
    op.create_index(op.f('ix_wastage_records_data_source'), 'wastage_records', ['data_source'], unique=False)
    op.create_foreign_key(None, 'wastage_records', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wastage_records', type_='foreignkey')
    op.drop_index(op.f('ix_wastage_records_data_source'), table_name='wastage_records')
    op.drop_column('wastage_records', 'data_source')
    op.drop_column('wastage_records', 'recorded_by')
    op.drop_column('wastage_records', 'notes')
    op.drop_column('wastage_records', 'department')
    op.drop_index(op.f('ix_supplier_deliveries_data_source'), table_name='supplier_deliveries')
    op.drop_column('supplier_deliveries', 'data_source')
    op.drop_column('storage_units', 'max_safe_temp_c')
    op.drop_column('storage_units', 'min_safe_temp_c')
    op.drop_constraint(None, 'storage_readings', type_='foreignkey')
    op.drop_index(op.f('ix_storage_readings_data_source'), table_name='storage_readings')
    op.drop_column('storage_readings', 'data_source')
    op.drop_column('storage_readings', 'recorded_by')
    op.drop_column('storage_readings', 'remarks')
    op.drop_index(op.f('ix_food_batches_data_source'), table_name='food_batches')
    op.drop_column('food_batches', 'data_source')
    op.drop_column('food_batches', 'quarantine_reason')
    op.drop_column('food_batches', 'is_quarantined')
    op.drop_constraint(None, 'consumption_records', type_='foreignkey')
    op.drop_constraint(None, 'consumption_records', type_='foreignkey')
    op.drop_index(op.f('ix_consumption_records_food_batch_id'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_data_source'), table_name='consumption_records')
    op.drop_column('consumption_records', 'data_source')
    op.drop_column('consumption_records', 'recorded_by')
    op.drop_column('consumption_records', 'department')
    op.drop_column('consumption_records', 'meal')
    op.drop_column('consumption_records', 'food_batch_id')
    op.drop_index(op.f('ix_inventory_transactions_ts'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_food_batch_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_data_source'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_occupancy_records_record_date'), table_name='occupancy_records')
    op.drop_index(op.f('ix_occupancy_records_data_source'), table_name='occupancy_records')
    op.drop_table('occupancy_records')
    # ### end Alembic commands ###
